---
title: "function_updated"
author: "Jasmine Cabrera"
format: html
editor: visual
---

# Functions (Updated: 04/18/2026)

## Libraries & Parallelization

```{r}
#| eval: false
library(tidyclust)
library(tidyverse)
library(tidymodels)
library(foreach)
library(doParallel)
library(MASS)

doParallel::registerDoParallel(cores = detectCores() - 5)
```

## Functions

### **simulate_mvn()**

```{r}
simulate_mvn <- function(n = 100, 
                         variance = 0.4,
                         desired_k = 3,
                         start_seed = 123){
  
  ### INPUT CHECKS:
  # n is an int
  if (n %% 1 != 0 || n <= 0) {
    stop("The number of observations, n, must be a positive integer.")}
  
  # variance is greater than 0
  if (variance <= 0) {
    stop("Variance must be greater than 0.")}
  
  # desired_k is an positive int
  if (desired_k %% 1 != 0 || desired_k < 1) {
    stop("The desired k value must be a positive integer.")}
  
  # desired_k is 1
  if (desired_k == 1) {
    warning("The desired k value is 1 (one cluster).")}
  
  # start seed is a positive int
  if (start_seed %% 1 != 0 || start_seed < 0) {
    stop("The seed value must be an integer.")}
  
  ### FUNCTION:
  set.seed(start_seed)
  
  # creating covariance matrix
  cov_matrix <- diag(2) * variance
  
  # obs per cluster
  n_per_cluster <- ceiling(n / desired_k)
  
  # distance between each cluster center
  separation <- 3
  
  # create grid coordinates for means
  grid_coords <- expand.grid(x = seq(0, by = separation,
                                     length.out = ceiling(sqrt(desired_k))),
                             y = seq(0, by = separation, 
                                     length.out = ceiling(sqrt(desired_k))))
    
  # pick first k grid points
  centers <- grid_coords[1:desired_k, ]
    
  # generate data
  sim_data <- do.call(rbind, lapply(1:desired_k, function(k){
      
  # determine mean
  mu <- c(centers$x[k], centers$y[k])
      
  # generate clusters
  MASS::mvrnorm(n = n_per_cluster,
                mu = mu,
                Sigma = cov_matrix)})) |>
    as.data.frame() |> 
    setNames(c("X1", "X2"))
  
  sim_data}
```

------------------------------------------------------------------------

### **buddies_matrix()**

```{r}
buddies_matrix <- function(data = data, 
                           k = 3,
                           subsample_prop = 0.8, 
                           num_subsamples = 10,
                           start_seed = 123, 
                           cluster_method){
  
  ### INPUT CHECKS:
  # data is a dataframe
  if (!is.data.frame(data)) {
    stop("Data must be in a dataframe.")}
  
  # k is a positive int
  if (k %% 1 != 0 || k < 1) {
    stop("The desired k value must be a positive integer.")}
  
  # k is 1
  if (k == 1) {
    warning("The desired k value is 1 (one cluster).")}
  
  # sub_sample prop is between 0 and 1
  if (subsample_prop <= 0 || subsample_prop >= 1) {
    stop("Subsample proportion needs to be between 0 and 1.")}
  
  #  num_subsamples is a positive int
  if (num_subsamples <= 0 || num_subsamples %% 1 != 0) {
    stop("The number of subsamples must be a positive integer.")}
  
  # clustering method is kmeans
  if (cluster_method != "kmeans"){
    stop("Error: Clustering method does not currently work. Please change to 'kmeans'.")}
  
  # start seed is a positive int
  if (start_seed %% 1 != 0 || start_seed < 0) {
    stop("The seed value must be an integer.")}
  
  ### FUNCTION:
  # parallelization
  cores <- max(1, parallel::detectCores() - 5)
  cl <- parallel::makeCluster(cores)
  doParallel::registerDoParallel(cl)
  on.exit(parallel::stopCluster(cl))
  
  # drop na and scale data
  data_clean <- data |>
    tidyr::drop_na() |>
    scale() |>
    as.data.frame() |>
    dplyr::mutate(index = dplyr::row_number())
  
  # initialize results list -- holds matrix for a given k
  results <- list()
  results <- foreach::`%dopar%`(foreach::foreach(i = 1:num_subsamples,
                     .packages = c("tidyclust", 
                                   "tidyverse", 
                                   "tidymodels")), {

                     # initalizing blank matrix     
                     result_matrix <- matrix(0, nrow = nrow(data_clean),
                                                ncol = nrow(data_clean))
                       
                     # seed
                     set.seed(start_seed + i)
                     
                     # resample
                     random_sample <- data_clean |>
                       filter(index %in% sample(index, floor(subsample_prop * nrow(data))))
                     
                     # clustering
                     if (cluster_method == "kmeans"){
                       model <- tidyclust::k_means(num_clusters = k) |>
                         tidyclust::fit(~ .,
                             data = random_sample[, !(names(random_sample) %in% "index")])}
                     
                     else{stop("Model option currently in progress.")}

                       
                     # assign points to cluster
                     intermediate <- data.frame(random_sample$index,
                                                tidyclust::extract_cluster_assignment(model) |>
                                                mutate(.cluster = as.character(.cluster)),
                                                stringsAsFactors = FALSE)
                       
                     # rename columns
                     colnames(intermediate) <- c("index", "cluster")
                     
                     # assign results matrix (-1, 1, 0)
                     for (c in unique(intermediate$cluster)){
                       idx <- intermediate[intermediate$cluster == c, ]$index
                      
                     if (length(idx) > 1){
                       idx <- sort(unlist(idx), method = "radix")
                       ones <- t(combn(idx, 2))
                       result_matrix[ones[, 1], ones[, 2]] <- 1}
                       
                     neg_one_idx <- expand.grid(idx, setdiff(random_sample$index, idx))
                     result_matrix[neg_one_idx[, 1], neg_one_idx[, 2]] <- -1}
                     
                     # set lower triangle and diagonal to NA
                     result_matrix[lower.tri(result_matrix, diag = TRUE)] <- NA
                      
                     return(result_matrix)})
                    
  # return results
  return(results)}
```

------------------------------------------------------------------------

### **mean_matrix()**

```{r}
mean_matrix <- function(data = data,
                        k = 3,
                        subsample_prop = 0.8,
                        num_subsamples = 10,
                        start_seed = 123,
                        cluster_method){
  
  ### INPUT CHECKS:
  # data is a dataframe
  if (!is.data.frame(data)) {
    stop("Data must be in a dataframe.")}
  
  # k is a positive int
  if (k %% 1 != 0 || k < 1) {
    stop("The desired k value must be a positive integer.")}
  
  # k is 1
  if (k == 1) {
    warning("The desired k value is 1 (one cluster).")}
  
  # sub_sample prop is between 0 and 1
  if (subsample_prop <= 0 || subsample_prop >= 1) {
    stop("Subsample proportion needs to be between 0 and 1.")}
  
  #  num_subsamples is a positive int
  if (num_subsamples <= 0 || num_subsamples %% 1 != 0) {
    stop("The number of subsamples must be a positive integer.")}
  
  # clustering method is kmeans
  if (cluster_method != "kmeans"){
    stop("Error: Clustering method does not currently work. Please change to 'kmeans'.")}
  
  # start seed is a positive int
  if (start_seed %% 1 != 0 || start_seed < 0) {
    stop("The seed value must be an integer.")}
  
  ### FUNCTION:
  # call buddies_matrix()
  results <- buddies_matrix(data, 
                            k = k,
                            subsample_prop = subsample_prop, 
                            num_subsamples = num_subsamples,
                            start_seed = start_seed,
                            cluster_method = cluster_method)
  
  # abs value the entire matrix for all matrices
  absolute_sum <- lapply(results, abs)
  
  # get sum of abs value in final matrix
  absolute_final <- absolute_sum |>
    purrr::reduce(`+`)
  
  # get sum of values in final matrix
  numerator <- results |>
    purrr::reduce(`+`)
  
  return(list(matrices = results, score = numerator/absolute_final))}
```

------------------------------------------------------------------------

### **similarity_score()**

```{r}
similarity_score <- function(mean_matrix = mean_mat){
  
  ### INPUT CHECKS:
  # check if list
  if (!is.list(mean_matrix)) {
    stop("Input must be a list (output from mean_matrix function).")}
  
  # correct element names
  required_names <- c("matrices", "score")
  if (!all(required_names %in% names(mean_matrix))) {
    stop("Input list is missing 'matrices' or 'score'. Did you provide the correct object?")}
  
  # check score is a matrix
  if (!is.matrix(mean_matrix$score)) {
    stop("The 'score' element must be a matrix.")}
  
  ### FUNCTION:
  # get score matrix
  mean_matrix_score <- mean_matrix$score 
  
  # transforms into vector
  result_vector <- as.vector(mean_matrix_score)
  
  # keeps only non NA values
  result_vector <- abs(result_vector[!is.na(result_vector)])
  
  # finds squared distance from one
  return(mean((1 - result_vector)**2))}
```

------------------------------------------------------------------------

### crab()

```{r}
crab <- function(data,
                 n = 100,
                 min_k = 2,
                 max_k = 5,
                 subsample_prop = 0.8,
                 num_subsamples = 10,
                 start_seed = 123,
                 cluster_method){

  ### INPUT CHECKS:
  # data is a dataframe
  if (!is.data.frame(data)) {
    stop("Data must be in a dataframe.")}
  
  # min_k is a positive int
  if (min_k %% 1 != 0 || min_k < 1) {
    stop("The minimum k value must be a positive integer.")}
  
  # min_k is 1
  if (min_k == 1) {
    warning("The minimum k value is 1 (one cluster).")}
  
  # min_k < max_k
  if (min_k >= max_k) {
    stop("The minimum k value must be less than the maximum k value.")}
  
  # max_k is a positive int
  if (max_k %% 1 != 0 || max_k < 1) {
    stop("The maximum k value must be a positive integer.")}
  
  # max_k is 1
  if (max_k == 1) {
    warning("The maximum k value is 1 (one cluster).")}
  
  # sub_sample prop is between 0 and 1
  if (subsample_prop <= 0 || subsample_prop >= 1) {
    stop("Subsample proportion needs to be between 0 and 1.")}
  
  #  num_subsamples is a positive int
  if (num_subsamples <= 0 || num_subsamples %% 1 != 0) {
    stop("The number of subsamples must be a positive integer.")}
  
  # clustering method is kmeans
  if (cluster_method != "kmeans"){
    stop("Error: Clustering method does not currently work. Please change to 'kmeans'.")}
  
  # start seed is a positive int
  if (start_seed %% 1 != 0 || start_seed < 0) {
    stop("The seed value must be an integer.")}
  
  ### FUNCTION:
  # intialize score list
  k_scores <- data.frame(k = numeric(),
                         Score = numeric(),
                         `Time (seconds)` = numeric(),
                         `Best Cluster (k)` = character(),
                         check.names = FALSE)

  # iterate over k values
  for (k in min_k:max_k){

    # start time
    tictoc::tic()

    # get buddies matrices and overall mean matrix
    mean_mat <- mean_matrix(data = data,
                            k = k,
                            subsample_prop = subsample_prop,
                            num_subsamples = num_subsamples,
                            start_seed = start_seed,
                            cluster_method = cluster_method)

    # store all scores
    score <- similarity_score(mean_matrix = mean_mat)

    # end time
    time_info <- tictoc::toc(quiet = TRUE)

    # calculate execution time
    elapsed_time <- time_info$toc - time_info$tic

    # add to results
    k_scores <- rbind(k_scores,
                      data.frame(k = k,
                                 Score = score,
                                 `Time (seconds)` = elapsed_time,
                                 `Best Cluster (k)` = " ",
                                 check.names = FALSE,
                                 stringsAsFactors = FALSE))}

  # find row with lowest score
  best_score_idx <- which.min(k_scores$Score)
  k_scores$`Best Cluster (k)`[best_score_idx] <- "BEST"
  
  # remove row names index
  rownames(k_scores) <- NULL
  
  # get similarity score
  return(k_scores)}
```

------------------------------------------------------------------------

### repeat_simulations()

```{r}
repeat_simulations <- function(crab_setup = NULL,
                               data = NULL,
                               num_runs,
                               n = 100,
                               variance, 
                               desired_k = 3, 
                               min_k,
                               max_k,
                               subsample_prop = 0.8, 
                               num_subsamples,
                               start_seed = 123,
                               cluster_method) {
  
  ### INPUT CHECKS:
  # data is a dataframe
  if (!is.null(data) && !is.data.frame(data)) {
    stop("Data must be in a dataframe.")}
  
  # both crab_setup or data is used
  if (!is.null(crab_setup) && !is.null(data)) {
    stop("Error: Specify either crab_setup OR data, not both.")}
  
  # either crab_setup or data is used
  if (is.null(crab_setup) && is.null(data) && missing(variance)) {
    stop("Error: You must provide a setup object, a dataset, or a variance to simulate data.")}
  
  
  
  # n is an int
  if (n %% 1 != 0 || n <= 0) {
    stop("The number of observations, n, must be a positive integer.")}
  
  # either variance (for simulate_mvn) or given data is used
  if (!is.null(crab_setup) && !missing(variance)) {
    stop("Error: Specify either crab_setup OR variance, not both.")}
  
  # missing variance and crab_setup
  if (is.null(crab_setup) && missing(variance)) {
  stop("Error: You must specify either crab_setup or variance.")} 
  
  # desired_k is an positive int
  if (desired_k %% 1 != 0 || desired_k < 1) {
    stop("The desired k value must be a positive integer.")}
  
  # desired_k is 1
  if (desired_k == 1) {
    warning("The desired k value is 1 (one cluster).")}
  
  
  
  # sub_sample prop is between 0 and 1
  if (subsample_prop <= 0 || subsample_prop >= 1) {
    stop("Subsample proportion needs to be between 0 and 1.")}
  
 
  
  # start seed is a positive int
  if (start_seed %% 1 != 0 || start_seed < 0) {
    stop("The seed value must be an integer.")}
  
  
  ### FUNCTION:
  # if crab_setup provided, use params
  if (!is.null(crab_setup)){
    
    # check params
    if (is.null(crab_setup$specified_params)){
        stop("Error: You have not specified your parameters. Call crab_sim_params() first.")}
    
    # assign params
    params <- crab_setup$specified_params
    num_runs = params$num_runs
    n = params$n
    min_k = params$min_k
    max_k = params$max_k
    subsample_prop = params$subsample_prop
    num_subsamples = params$num_subsamples
    cluster_method = params$cluster_method
    variance = params$variance
    desired_k = params$desired_k
    
    # if no data provided
    if (is.null(data)){
      data <- crab_setup$data}}
  
  # num_runs is a positive int
  if (num_runs %% 1 != 0 || num_runs < 1) {
    stop("The number of runs value must be a positive integer.")}
  
  # num_runs is 1
  if (num_runs == 1) {
    warning("The number of runs value is 1.")}
  
  # min_k is a positive int
  if (min_k %% 1 != 0 || min_k < 1) {
    stop("The minimum k value must be a positive integer.")}
  
  # min_k is 1
  if (min_k == 1) {
    warning("The minimum k value is 1 (one cluster).")}
  
  # min_k < max_k
  if (min_k >= max_k) {
    stop("The minimum k value must be less than the maximum k value.")}
  
  # max_k is a positive int
  if (max_k %% 1 != 0 || max_k < 1) {
    stop("The maximum k value must be a positive integer.")}
  
  # max_k is 1
  if (max_k == 1) {
    warning("The maximum k value is 1 (one cluster).")}
  
  #  num_subsamples is a positive int
  if (num_subsamples <= 0 || num_subsamples %% 1 != 0) {
    stop("The number of subsamples must be a positive integer.")}
  
  # clustering method is kmeans
  if (cluster_method != "kmeans"){
    stop("Error: Clustering method does not currently work. Please change to 'kmeans'.")}
  
  # initialize results list
  results_list <- list()
  counter <- 1
  
  # loop through variances
  for (var in variance) {
    
    # variance is greater than 0
    if (var <= 0) {
    stop("Variance must be greater than 0.")}
    
     # simulate data if crab_setup was not provided
      if (is.null(data)) {
          sim_data <- simulate_mvn(n = n,
                                   variance = var, 
                                   desired_k = desired_k)}
      else {sim_data <- data}
    
    # loop through number of runs/reps
    for (i in seq_len(num_runs)) {
      
      # alternate seed
      current_seed <- start_seed + i
      
      # call crab()
      sim_result <- crab(data = sim_data,
                         start_seed = current_seed,
                         n = n,
                         min_k = min_k,
                         max_k = max_k,
                         subsample_prop = subsample_prop, 
                         num_subsamples = num_subsamples,
                         cluster_method = cluster_method)
      
      # add rep and variance identifier
      sim_result$run <- i
      sim_result$var <- var
      
      # store result
      results_list[[counter]] <- sim_result
      counter <- counter + 1}}
  
  # combine all results and get rid of index row names
  all_results <- do.call(rbind, results_list)
  rownames(all_results) <- NULL
  
  return(all_results)}
```

------------------------------------------------------------------------

### crab_prep()

```{r}
crab_prep <- function(data){
  
  ### INPUT CHECKS:
  if (!is.data.frame(data)) {
    stop("Data must be in a dataframe.")}
  
  ### FUNCTION:
  # grab all columns, leave user choices NULL
  data_info <- list(data = data, 
                    original_cols = colnames(data),
                    specified_cols = NULL,
                    specified_params = list())
  
  return(data_info)}
```

------------------------------------------------------------------------

### crab_cols()

```{r}
crab_cols <- function(data_info, chosen_cols){
  ### INPUT CHECKS:
  # check if data_info is a list
  if (!is.list(data_info)) {
    stop("Input must be a list (output from crab_prep function).")}
  
  # correct element names
  required_names <- c("data", "original_cols", "specified_cols", "specified_params")
  if (!all(required_names %in% names(data_info))) {
    stop("Input list is missing at least one of the following: 'data', 'original_cols', 'specified_cols', 'specified_params.' Did you provide the correct object?")}
  
  # check data is a dataframe
  if (!is.data.frame(data_info$data)) {
    stop("The 'data' element must be a dataframe.")}
  
  # check original_cols
  if (!is.character(data_info$original_cols)) {
    stop("original_cols must be a character vector of column names.")}
  
  # check chosen_cols is a character
  if (!is.character(chosen_cols)) {
    stop("chosen_cols must be a character vector of column names.")}
  
  ### FUNCTION:
  # check if chosen columns exist
  missing_cols <- setdiff(chosen_cols, data_info$original_cols)
  
  # leave error message if columns dont exist
  if (length(missing_cols) > 0) {
    stop("Column(s) do not exist: ",
         paste(missing_cols, collapse = ", "))}
  
  # update specified cols
  data_info$specified_cols <- chosen_cols
  
  return(data_info)}
```

------------------------------------------------------------------------

### crab_params()

```{r}
crab_params <- function(data_info, min_k, max_k, num_subsamples, 
                        subsample_prop = 0.8, cluster_method){
  
  ### INPUT CHECKS:
  # check if data_info is a list
  if (!is.list(data_info)) {
    stop("Input must be a list (output from crab_prep function).")}
  
  # correct element names
  required_names <- c("data", "original_cols", "specified_cols", "specified_params")
  if (!all(required_names %in% names(data_info))) {
    stop("Input list is missing at least one of the following: 'data', 'original_cols', 'specified_cols', 'specified_params.' Did you provide the correct object?")}
  
  # check data is a dataframe
  if (!is.data.frame(data_info$data)) {
    stop("The 'data' element must be a dataframe.")}
  
  # check original_cols is a list
  if (!is.character(data_info$original_cols)) {
    stop("original_cols must be a character vector of column names.")}
  
  # min_k is a positive int
  if (min_k %% 1 != 0 || min_k < 1) {
    stop("The minimum k value must be a positive integer.")}
  
  # min_k is 1
  if (min_k == 1) {
    warning("The minimum k value is 1 (one cluster).")}
  
  # min_k < max_k
  if (min_k >= max_k) {
    stop("The minimum k value must be less than the maximum k value.")}
  
  # max_k is a positive int
  if (max_k %% 1 != 0 || max_k < 1) {
    stop("The maximum k value must be a positive integer.")}
  
  # max_k is 1
  if (max_k == 1) {
    warning("The maximum k value is 1 (one cluster).")}
    
  # sub_sample prop is between 0 and 1
  if (subsample_prop <= 0 || subsample_prop >= 1) {
    stop("Subsample proportion needs to be between 0 and 1.")}
  
  #  num_subsamples is a positive int
  if (num_subsamples <= 0 || num_subsamples %% 1 != 0) {
    stop("The number of subsamples must be a positive integer.")}
  
  # clustering method is kmeans
  if (cluster_method != "kmeans"){
    stop("Error: Clustering method does not currently work. Please change to 'kmeans'.")}
  
  ### FUNCTION:
  # update specified params
  data_info$specified_params <- list(
    min_k = min_k,
    max_k = max_k,
    num_subsamples = num_subsamples,
    subsample_prop = subsample_prop,
    cluster_method = cluster_method)
  
  return(data_info)}
```

------------------------------------------------------------------------

### crab_sim_params()

```{r}
crab_sim_params <- function(data_info, min_k, max_k, num_subsamples, 
                            n = 100, variance, desired_k = 3, 
                            subsample_prop = 0.8, num_runs, cluster_method){
  ### INPUT CHECKS:
  # check min_k and max_k
  if (min_k > max_k){
    stop("Error: min_k must be <= max_k.")}
    
  if (min_k < 0){
    stop("Error: min_k must be > 0.")}
  
  if (max_k < 0){
    stop("Error: max_k must be > 0.")}
  
  # check subsample prop
  if (subsample_prop >= 1){
    stop("Error: subsample_prop must be < 1.")}
  
  # check num_runs
  if (num_runs < 0){
    stop("Error: num_runs must be > 0.")}
  
  # check cluster method
  if (cluster_method != "kmeans"){
    stop("Error: Clustering method does not currently work. Please change to 'kmeans'.")}
  
  ### FUNCTION:
  # update specified params
  data_info$specified_params <- list(
    min_k = min_k,
    max_k = max_k,
    num_subsamples = num_subsamples,
    n = n,
    variance = variance,
    desired_k = desired_k,
    subsample_prop = subsample_prop,
    num_runs = num_runs,
    cluster_method = cluster_method)
  
  return(data_info)}
```

------------------------------------------------------------------------

### crab_bake()

```{r}
crab_bake <- function(data_info){
  
  ### INPUT CHECKS:
   # check if data_info is a list
  if (!is.list(data_info)) {
    stop("Input must be a list (output from crab_prep function).")}
  
  # correct element names
  required_names <- c("data", "original_cols", "specified_cols", "specified_params")
  if (!all(required_names %in% names(data_info))) {
    stop("Input list is missing at least one of the following: 'data', 'original_cols', 'specified_cols', 'specified_params.' Did you provide the correct object?")}
  
  # check data is a dataframe
  if (!is.data.frame(data_info$data)) {
    stop("The 'data' element must be a dataframe.")}
  
  # check original_cols is a list
  if (!is.character(data_info$original_cols)) {
    stop("original_cols must be a character vector of column names.")}
  
  # check specified_params is a list
  if (!is.list(data_info$specified_params)) {
    stop("The 'specified_params' element must be a list.")}
  
  # check cols are chosen
  if (is.null(data_info$specified_cols)){
    stop("No columns have been specified. Call crab_cols() first.")}
  
  # check params are chosen
  if (is.null(data_info$specified_params)){
    stop("No parameters have been specified. Call crab_params() first.")}

  ### FUNCTION:
  # grab data with chosen cols
  crab_data <- data_info$data[, data_info$specified_cols, drop = FALSE]
  
  # grab params
  params <- data_info$specified_params
  
  # call crab()
  score <- crab(data = crab_data,
                min_k = params$min_k,
                max_k = params$max_k,
                subsample_prop = params$subsample_prop,
                num_subsamples = params$num_subsamples,
                cluster_method = params$cluster_method)
  
  return(score)}
```

------------------------------------------------------------------------

### get_pointvec()

```{r}
get_pointvec <- function(i, mean_matrix_score) {
  ### INPUT CHECKS:
  
  # check score is a matrix
  if (!is.matrix(mean_matrix_score)) {
    stop("The 'score' element must be a matrix.")}
  
  # check i is an integer
  if (i %% 1 != 0 || i < 1) {
    stop("Point must be a positive integer.")}
  
  ### FUNCTION:
  # grab i row and col, without diagonal
  row <- mean_matrix_score[i, -i]
  col <- mean_matrix_score[-i, i]
  
  # grab all abs vals of i, removing NAs
  res_vec <- c(row, col)
  res_vec <- abs(res_vec[!is.na(res_vec)])
  return(res_vec)}
```

### point_contribution()

```{r}
point_contribution <- function(data, mean_matrix) {
  ### INPUT CHECKS:
  # check if list
  if (!is.list(mean_matrix)) {
    stop("Input must be a list (output from mean_matrix function).")}
  
  # correct element names
  required_names <- c("matrices", "score")
  if (!all(required_names %in% names(mean_matrix))) {
    stop("Input list is missing 'matrices' or 'score'. Did you provide the correct object?")}
  
  # check score is a matrix
  if (!is.matrix(mean_matrix$score)) {
    stop("The 'score' element must be a matrix.")}
  
  # data is a dataframe
  if (!is.data.frame(data)) {
    stop("Data must be in a dataframe.")}
  
  ### FUNCTION:
  # loop through every point
  scores <- lapply(c(1:nrow(data)), function(i) {
    
    # abs vals of i
    full_vec <- get_pointvec(i, mean_matrix$score)
    
    # computer score
    singlePointScore <- mean((1 - full_vec)^2)
    return(list(index = i, singlePointScore = singlePointScore))})
  
  # create data frame
  final_df <- do.call(rbind.data.frame, scores)
  
  # mean score
  total_score <- mean(final_df$singlePointScore)

  # sigmoid fn
  sigmoid <- function(x) 1 / (1 + exp(-x))

  # point contribution
  final_df <- final_df |>
    mutate(singlePointContribution = sigmoid(singlePointScore / total_score))
  
  return(final_df)}
```
