#' Create Mean Matrix
#'
#' @description
#' Computes a consistency score matrix for a specified k by measuring how
#' frequently each pair of observations is clustered together across subsamples.
#' Each element in the score matrix represents the sum of corresponding -1 and 1
#' values across subsamples, divided by the total number of valid comparisons.
#' This approach excludes zeros, which indicate observations not included in a
#' given resample. The function calls buddies_matrix() to obtain the matrices
#' for this calculation.
#'
#' @param data
#' The dataset to be analyzed
#'
#' @param k
#' The specific number of clusters (k) to evaluate
#'
#' Defaults to 3.
#'
#' @param subsample_prop
#' Proportion of the dataset to use for each subsample
#'
#' Defaults to 0.8
#'
#' @param num_subsamples
#' Number of subsamples to generate
#'
#' Defaults to 10
#'
#' @param start_seed
#' Random seed for reproducibility
#'
#' Defaults to 123
#'
#' @param cluster_method
#' Specified clustering algorithm
#'
#' @returns
#' Produces a list of two elements. The first element, results, stores the
#' matrices generated by buddies_matrix(). The second element, score, represents
#' the final mean consistency matrix calculated from those results.
#'
#' @export
#'
#' @examples
#' data <- simulate_mvn(n = 10)
#' mean_matrix(data = data, k = 3, subsample_prop = 0.8, num_subsamples = 3,
#'             cluster_method = "kmeans")

mean_matrix <- function(data = data,
                        k = 3,
                        subsample_prop = 0.8,
                        num_subsamples = 10,
                        start_seed = 123,
                        cluster_method = "kmeans"){

  # call simulate_cluster() function
  results <- buddies_matrix(data,
                            k = k,
                            subsample_prop = subsample_prop,
                            num_subsamples = num_subsamples,
                            start_seed = start_seed,
                            cluster_method = cluster_method)

  # abs value the entire matrix for all matrices
  absolute_sum <- lapply(results, abs)

  # get sum of abs value in final matrix
  absolute_final <- absolute_sum |>
    purrr::reduce(`+`)

  # get sum of values in final matrix
  numerator <- results |>
    purrr::reduce(`+`)

  return(list(matrices = results, score = numerator/absolute_final))}
